#!/bin/bash

exec &> /tmp/PostprocessBuildPlayerLogs.txt

# Find all other PostprocessBuildPlayer_* scripts and execute them
for file in `find ./Assets/Editor -regex ".*PostprocessBuildPlayer_.*" -maxdepth 1 -print 2>/dev/null`
do
    if [[ $file != *"meta"* ]]
    then
	    if [[ $file != *"ExternalXcode"* ]]
	    then
			echo $file
			$file "$@"
		end
    fi
done

./Assets/Editor/PostprocessBuildPlayer_ExternalXcode1 "$@"
./Assets/Editor/PostprocessBuildPlayer_ExternalXcode2 "$@"
